### ISSUE TITLE
Flutter web support?

### ISSUE THREAD

**Issue by CiriousJoker** [aryzhov/flutter-expandable#18]
It currently depends on flutter, so it can't be used in flutter_web.

Will this change anytime soon?

In the meantime, here is my fork with the changed dependencies:

https://github.com/CiriousJoker/flutter-expandable

**Comment by aryzhov** [comment]
The support for flutter_web exists in the **flutter_web** branch. You just have to reference the github repo directly in `pubspec.yaml`:

```
dependencies:
  expandable: 

dependency_overrides:
  expandable:
    git:
      url: https://github.com/aryzhov/flutter-expandable.git
      ref: flutter_web
```
